### ISSUE TITLE
Check for allocation success before using buffer.

### ISSUE THREAD

**Issue by JohnLaTwC** [Neo23x0/Raccine#10]
https://github.com/Neo23x0/Raccine/blob/b8ea99ad4b4e393b3cab2639b33755a26d3a8868/raccine.cpp#L58

Think you're missing a check for allocation success before using the buffer.
if (!pTIL) 
     return 0

**Comment by Neo23x0** [comment]
Thanks, fixed in https://github.com/Neo23x0/Raccine/commit/137da0e88d76bcf36f65fb5d5da40ba30b8bfcf7
