### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by adoello** [Neo23x0/Raccine#124]
Version 1.4.2 installs correctly, but in version 1.4.3, the installer doesn't open. When I open Raccine.exe it does not open. When I open install-raccine.bat it gives the following error: 

> WARNING: you may have downloaded the source code only or an Antivirus has deleted an important part of the package
Make sure to download a package that contains the compiled binaries by downloading a package from the RELEASE section.
>   https://github.com/Neo23x0/Raccine/releases
> The installer will exit now ..

Thanks

**Comment by Neo23x0** [comment]
Hi, thanks for the report. I hope that it's fixed in version 1.4.4
https://github.com/Neo23x0/Raccine/releases/tag/1.4.4

**Comment by adoello** [comment]
Hello @Neo23x0 
Now, it's working well. Thank you very much.
