### ISSUE TITLE
Prometheus / Thanos Ransomware kills Raccine process

### ISSUE THREAD

**Issue by certrik** [Neo23x0/Raccine#126]
In an article from Unit42 it is described that at least Prometheus / Thanos Ransomware actively tries killing Raccine processes in order to operate. https://unit42.paloaltonetworks.com/prometheus-ransomware/

It seems that Raccine will be needing advanced evasion techniques starting now in order to still be effective.

**Comment by Neo23x0** [comment]
This shouldn't be a problem anymore. 
Newer versions of Raccine also intercept calls to taskkill.exe and kill the process that try to kill Raccine.
