### ISSUE TITLE
Convert code to modern C++

### ISSUE THREAD

**Issue by Eran-YT** [Neo23x0/Raccine#28]
The code is currently C with some C++ parts, would you want to convert it to modern C++ code?

**Comment by Omodaka9375** [comment]
You mean implement some classes? :)

**Comment by Eran-YT** [comment]
Mostly a handle wrapper, and some other c++ cleanups (removing redundant copying, using c++ style casts, ...)

**Comment by Neo23x0** [comment]
Hi @Eran-YT, the newest development happens on the `gui` branch, on which we even change the type of the application from Console to Windows application. 
Help is always welcome.
