### ISSUE TITLE
Empty Event Message

### ISSUE THREAD

**Issue by Neo23x0** [Neo23x0/Raccine#44]
I can't figure out under which circumstances this "empty" message would be produced. 
Could someone of you find the location where this happens? 

@JohnLaTwC @Eran-YT @Omodaka9375 ?

![Screenshot 2020-10-21 164044](https://user-images.githubusercontent.com/2851492/96735786-3641e680-13bc-11eb-8205-e1d526bfbee8.png)

**Comment by JohnLaTwC** [comment]
It comes from the install script:
eventcreate.exe /L Application /T Information /id 1 /so Raccine /d "Raccine event message"

**Comment by JohnLaTwC** [comment]
notice the eventId is 1.  raccine.exe always logs with #define RACCINE_EVENTID_MALICIOUS_ACTIVITY  2.  The only place 1 is used is in the eventcreate in the install.  You could change the message in the installer to say something like "Raccine registration of event id %x"

**Comment by Neo23x0** [comment]
Oh my ... yes! I'll change it to a more descriptive message. Thanks
