### ISSUE TITLE
C:\ProgramData\Raccine\Raccine_log.txt is first created with privileges of the task that triggered it

### ISSUE THREAD

**Issue by wdormann** [Neo23x0/Raccine#47]
If C:\ProgramData\Raccine\Raccine_log.txt is created because of a program written to with elevated privileges, that log file will  require elevated privileges to be written to.  Similarly, if the log file is created by one user, the log file cannot be written to as another user.

Ideally, if Raccine_log.txt is to be created, it should be created in a way that allows it to be written to regardless of privilege level or specific user that triggered its creation.

**Comment by Omodaka9375** [comment]
Originally the log file was created in C:\Windows together with the Raccine.exe file. So it was necessary to run with elevated privileges to write to file. This can be refactored after stabilization.

**Comment by Neo23x0** [comment]
Trying to fix this by creating an empty log file and giving every user write access to it. 
https://github.com/Neo23x0/Raccine/commit/2d43aa53f2939ed070477e6165fad995714c6657
