### ISSUE TITLE
Wrong YARA Dir - Can't fix

### ISSUE THREAD

**Issue by Neo23x0** [Neo23x0/Raccine#61]
Note: Working on the new branch `yara-ext-vars` with changes by @JohnLaTwC 

I am trying to figure out, why the rule matching process gets the wrong YARA rule directory. 
It uses `C:\ProgramData\Raccine` instead of `C:\ProgramData\Raccine\yara` 

![Screenshot 2020-10-24 101848](https://user-images.githubusercontent.com/2851492/97077247-61a61a80-15e2-11eb-99ff-8ea1b6913b36.png)

Can someone explain to me, why the class definition expects two variables: yara_rules_dir, raccine_program_directory
https://github.com/Neo23x0/Raccine/blob/yara-ext-vars/source/RaccineLib/YaraRuleRunner.cpp#L7

![Screenshot 2020-10-24 101226](https://user-images.githubusercontent.com/2851492/97077277-9914c700-15e2-11eb-8ace-bd13e8e4a7c4.png)

and the object instantiated from that class uses different values? https://github.com/Neo23x0/Raccine/blob/yara-ext-vars/source/RaccineLib/raccine.cpp#L49
Is that the wrong location? 

![Screenshot 2020-10-24 101251](https://user-images.githubusercontent.com/2851492/97077294-c6fa0b80-15e2-11eb-8030-83ce1e44412f.png)

**Comment by Neo23x0** [comment]
Ah, the `wTestFilename` name is misleading. 
I fixed it in: https://github.com/Neo23x0/Raccine/commit/0079ece73a5b5021bf87342d38945835fb523d3a

**Comment by Eran-YT** [comment]
You have both parameters in the class because the yara executable and the yara rules are in different directories
