### ISSUE TITLE
Branch `yara-ext-vars` Raccine-Test issues

### ISSUE THREAD

**Issue by Neo23x0** [Neo23x0/Raccine#67]
@Eran-YT : after merging changes from John, da I got offline, I noticed build problems on the `yara-ext-vars` branch, which we'd like to merge soon. Could you please check that branch and help us with the merge into your new code in main? 

![image](https://user-images.githubusercontent.com/2851492/97106498-48749b00-16c2-11eb-919b-55082a337231.png)

**Comment by Neo23x0** [comment]
I've created a pull request
https://github.com/Neo23x0/Raccine/pull/68

**Comment by Eran-YT** [comment]
I’ll look into it in a few hours
