### ISSUE TITLE
Suspended processes doesn't resume

### ISSUE THREAD

**Issue by Neo23x0** [Neo23x0/Raccine#76]
@Eran-YT : since your latest refactoring, not all suspended processes don't get resumed anymore 

https://github.com/Neo23x0/Raccine/commit/a385f3063c62e4991f4030a1219d19efbdd60af8

It doesn't happen all the time, but in 50% of the cases that I've tested. 

![Screenshot 2020-10-26 234941](https://user-images.githubusercontent.com/2851492/97236694-f167e680-17e5-11eb-81dc-051126386c74.png)

![image](https://user-images.githubusercontent.com/2851492/97236758-14929600-17e6-11eb-886e-8660430ab0c4.png)

**Comment by Neo23x0** [comment]
I tried to fix it with this commit https://github.com/Neo23x0/Raccine/commit/6c3c8a1710c917bb038d425335482da0cfcf0985

I am still not sure why it was there.

**Comment by Neo23x0** [comment]
It still suspends processes indefinitely

e.g. Running VSCode with Powershell integration looks like this:

![image](https://user-images.githubusercontent.com/2851492/97278965-a88e4d00-183a-11eb-9cd0-fa906a103be8.png)

![Screenshot 2020-10-27 095505](https://user-images.githubusercontent.com/2851492/97278899-97ddd700-183a-11eb-9bff-b4e0a6a769a9.png)

![image](https://user-images.githubusercontent.com/2851492/97278989-af1cc480-183a-11eb-8e77-05085852aebe.png)

**Comment by Eran-YT** [comment]
I'll try to fix it
