### ISSUE TITLE
PowerShell Invocation Fails

### ISSUE THREAD

**Issue by Neo23x0** [Neo23x0/Raccine#80]
VSCode runs the following command when activating the PowerShell console in the tool:

![Screenshot 2020-10-27 175833](https://user-images.githubusercontent.com/2851492/97335889-a817a580-187e-11eb-8151-4500d5367015.png)

```
ParentImage: C:\Program Files\Raccine\Raccine.exe
ParentCommandLine: "C:\Program Files\Raccine\Raccine.exe" C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner \"=====> PowerShell Integrated Console v2020.6.0 <=====
\" -LogLevel 'Normal' -LogPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1603817771-53060d3f-4aaa-471a-b244-75ec384fd3381603817770136\EditorServices.log' -SessionDetailsPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-9564-717768' -FeatureFlags @() "
```

Note that there's a line break after `-StartupBanner \"=====> PowerShell Integrated Console v2020.6.0 <=====` and before `\" -LogLevel 'Normal'`, which is very strange. 

![image](https://user-images.githubusercontent.com/2851492/97336030-d5645380-187e-11eb-9fdd-43325dd44e31.png)

I can also see this line break when I run it without Raccine intercepting (uninstalled Raccine) but in this case the invocation doesn't fail.

```
OriginalFileName: PowerShell.EXE
CommandLine: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner \"=====> PowerShell Integrated Console v2020.6.0 <=====
\" -LogLevel 'Normal' -LogPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1603818394-dddb2ceb-023c-4862-b7c2-d3695d91c4691603818393174\EditorServices.log' -SessionDetailsPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-12880-355229' -FeatureFlags @() "
``` 

This seems to be something to report to the VSCode team as well. @JohnLaTwC

**Comment by JohnLaTwC** [comment]
Can you share the 4688 event for the powershell process in the case where raccine is installed?

**Comment by Neo23x0** [comment]
Here you go: 

```
Process Information:
	New Process ID:		0x2b7c
	New Process Name:	C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
	Token Elevation Type:	%%1938
	Mandatory Label:		Mandatory Label\Medium Mandatory Level
	Creator Process ID:	0x5308
	Creator Process Name:	C:\Program Files\Raccine\Raccine.exe
	Process Command Line:	C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2020.6.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\modules' -EnableConsoleRepl -StartupBanner "=====> PowerShell Integrated Console v2020.6.0 <=====
" -LogLevel 'Normal' -LogPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\logs\1603822235-155ded5b-78c1-49bf-ba2f-955970d83b161603822222793\EditorServices.log' -SessionDetailsPath 'c:\Users\venom\.vscode\extensions\ms-vscode.powershell-2020.6.0\sessions\PSES-VSCode-24232-573280' -FeatureFlags @()  
```

**Comment by Neo23x0** [comment]
Ah, sorry - you asked for the log before that line. One moment.

**Comment by Neo23x0** [comment]
I've been experimenting a bit with that command line. 
I tried to run it exactly as it is shown in the 4688 eventlog and got an error. 
The error seems to be related to the `<` symbol within the Startup banner in that expression. 

![Screenshot 2020-10-27 193006](https://user-images.githubusercontent.com/2851492/97346209-748f4800-188b-11eb-946f-cfd0db65e5b4.png)

![Screenshot 2020-10-27 193422](https://user-images.githubusercontent.com/2851492/97346225-7822cf00-188b-11eb-9bc5-86ce8381ab0e.png)

**Comment by Neo23x0** [comment]
Well, with the latest changes, it starts at least, although I don't know if it is fully functional. 

Without Raccine:
![Screenshot 2020-10-27 193740](https://user-images.githubusercontent.com/2851492/97346628-f7180780-188b-11eb-9682-593015352390.png)

With Raccine:
![Screenshot 2020-10-27 193832](https://user-images.githubusercontent.com/2851492/97346732-1a42b700-188c-11eb-953e-1a42112cde49.png)

**Comment by JohnLaTwC** [comment]
I see VS Code launch powershell, but it does not have the command line you describe.  Do you have a way to repro?
![image](https://user-images.githubusercontent.com/16035087/97453004-91129b00-18f2-11eb-9fd2-5e6fafff11fe.png)

**Comment by Neo23x0** [comment]
Did you set the values to include all command line parameters? 
```
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" /v ProcessCreationIncludeCmdLine_Enabled /t REG_DWORD /d 1 /f
```

Do you see that banner "====> Powershell Integrated Console ...`  in your lower console section in VSCode? 
That banner is passed via command line params. That's why I ask.

**Comment by JohnLaTwC** [comment]
yes it is:

> reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit
    ProcessCreationIncludeCmdLine_Enabled    REG_DWORD    0x1

**Comment by JohnLaTwC** [comment]
With no raccine this is what I see:
![image](https://user-images.githubusercontent.com/16035087/97477204-8bc24a00-190c-11eb-8972-2f9cac7c9863.png)

**Comment by JohnLaTwC** [comment]
VSCode version info:
```
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
```

**Comment by Neo23x0** [comment]
Strange ... I have this standard extension installed

![image](https://user-images.githubusercontent.com/2851492/97477557-111b1e00-1950-11eb-8eb6-7f97bcb6d1b9.png)

Ah, maybe is caused by this dropdown - but I didn't select one of these consoles deliberately. There is "powershell" and "Powershell Integrated Console". 

![image](https://user-images.githubusercontent.com/2851492/97477802-5e978b00-1950-11eb-8e9e-222820062b0e.png)

**Comment by Neo23x0** [comment]
Well, I don't see this as a no-go for a new version 1.1 BETA. 
I have written more robot tests and most of them work as expected in the Github workflows. 
They'll help us see missing blocks, suspended processes or similar issues directly in future pull requests.

**Comment by JohnLaTwC** [comment]
I found the extension. Now, I see it.  Let me take a look.

**Comment by Neo23x0** [comment]
I'd say, it is a parser bug in the DLL that translates the EventData field into a valid Windows event message. It has a problem with the `<` character in the command line params and somehow inserts a new line character when parsing the XML structure.

**Comment by JohnLaTwC** [comment]
Try the drop I just emailed you.

**Comment by Neo23x0** [comment]
🤔

![raccine-psbug](https://user-images.githubusercontent.com/2851492/97496231-f73a0500-1968-11eb-8953-47f2eb2a3798.gif)

![Screenshot 2020-10-28 215917](https://user-images.githubusercontent.com/2851492/97496246-fb662280-1968-11eb-8279-9c4a65165dee.png)
